import { makeStyles } from "@material-ui/core";

export default makeStyles((theme) => ({
  contactDetails: {
    backgroundColor: "#ffffff",
    padding: "10px",
    borderRadius: "10px",
    boxShadow: "0 0 6px 3px #0000006b",
    [theme.breakpoints.down("sm")]: {
      boxShadow: "0 0 10px #000",
    },
    marginBlock: "10px",
  },
  head: {
    display: "flex",
    justifyContent: "space-between",
    flexFlow: "row",
  },
  bigAvatar: {
    width: "100px",
    height: "100px",
    fontSize: "60px",
    marginInline: "16px",
    marginBlock: "10px",
  },
  header: {
    alignSelf: "center",
    margin: "9px",
    transform: "translate(0%, 0)",
    width: "70%",
    fontSize: "28px",
    fontWeight: "400",
    color: "#323130",
    float: "left",
    fontFamily: "monospace",
  },
  editButton: {
    width: "150px",
    height: "50px",
    alignSelf: "flex-start",
    float: "right",
    fontVariant: "common-ligatures",
    textTransform: "capitalize",
    padding: "4px",
  },
  break: {
    width: "80%",
    height: "1px",
    background: "#ccd",
  },
  detailsContainer: {
    maxHeight: "460px",
    overflowY: "auto",
    paddingInline: "5px",
  },
  details: {
    padding: "10px",
    border: "2px solid #dadce0",
    borderRadius: "10px",
    marginBlock: "10px",
  },
  email: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    marginInline: "0",
    paddingInline: "4px",
    borderRadius: "8px",
    width: "auto",
    float: "left",
    alignItems: "center",
    padding: "8px",
  },
  emailText: {
    maxWidth: "520px",
    width: "80%",
    marginLeft: "5px",
    marginBlock: "5px",
    color: "#5c5cff",
  },
  notes: {
    background: "#ffffff",
    paddingInline: "15px",
    paddingBlock: "8px",
    margin: "0px",
    border: "2px solid #dadce0",
    borderRadius: "10px",
    display: "flex",
    justifyContent: "space-between",
    flexDirection: "column",
    alignItems: "center",
  },
  addNotes: {
    width: "150px",
    height: "50px",
    marginBlock: "10px",
    alignSelf: "center",
    textTransform: "capitalize",
  },
  phone: {
    display: "flex",
    flexDirection: "row",
    borderRadius: "10px",
    marginBlock: "2px",
    padding: "8px",
    width: "auto",
  },
  phoneNum: {
    margin: "0",
    fontWeight: "600",
    color: "#5c5cff",
    borderRight: "2px solid #161414",
    paddingRight: "10px",
  },
  phoneType: {
    marginInline: "10px",
    textTransform: "capitalize",
  },
  addPhone: {
    width: "100px",
    textTransform: "capitalize",
    height: "45px",
    padding: "5px",
    alignSelf: "center",
    marginInline: "6px",
  },
  overlay: {
    background: "#000000a6",
    position: "fixed",
    left: "0",
    top: "0",
    width: "100%",
    height: "100%",
    zIndex: "1000",
  },
  form: {
    position: "fixed",
    left: "20%",
    top: "30%",
    transform: "translate(50%, 50%)",
    backgroundColor: "#fff",
    border: "1px solid",
    borderColor: "#ccc",
    padding: "7px",
    borderRadius: "5px",
    zIndex: "1001",
  },
  close: {
    position: "absolute",
    top: "-27%",
    left: "-10%",
    fontSize: "30px",
    color: "#f50057",
  },
  loadingPaper: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    padding: "20px",
    borderRadius: "15px",
    height: "39vh",
    margin: "20px",
  },
  icons: {
    width: "34%",
    position: "relative",
    left: "2%",
    float: "left",
  },
}));
